//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentResidence.BL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public student()
        {
            this.studentsrooms = new HashSet<studentsroom>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string middlename { get; set; }
        public string surname { get; set; }
        public System.DateTime birthday { get; set; }
        public string phonenumber { get; set; }
        public int course { get; set; }
        public string studentgroup { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<studentsroom> studentsrooms { get; set; }
    }
}
